server:
  servlet:
    context-path: /


management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: logic-1
  datasource:
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create #create, create=drop




